apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: krew
spec:
  version: "v0.3.4"
  homepage: https://sigs.k8s.io/krew
  shortDescription: Package manager for kubectl plugins.
  caveats: |
    krew is now installed! To start using kubectl plugins, you need to add
    krew's installation directory to your PATH:

      * macOS/Linux:
        - Add the following to your ~/.bashrc or ~/.zshrc:
            export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
        - Restart your shell.

      * Windows: Add %USERPROFILE%\.krew\bin to your PATH environment variable

    To list krew commands and to get help, run:
      $ kubectl krew
    For a full list of available plugins, run:
      $ kubectl krew search

    You can find documentation at https://sigs.k8s.io/krew.

  platforms:
  - uri: https://github.com/kubernetes-sigs/krew/releases/download/v0.3.4/krew.tar.gz
    sha256: 6629b1d7ad215322361f8dd270396fd1a23555fdbde8dcc1ba4ad860978b319a
    bin: krew
    files:
    - from: ./krew-linux_amd64
      to: krew
    - from: ./LICENSE
      to: .
    selector:
      matchLabels:
        os: linux
        arch: amd64