#!/usr/bin/env bash

# https://unix.stackexchange.com/questions/281858/difference-between-xinitrc-xsession-and-xsessionrc

export TERMINAL="xst"
export XINITRC="runned"

# It fucks up if runned on i3
setxkbmap -model thinkpad60 -layout br

xmodmap $HOME/.xmodmap

exec i3
