# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports = [
    <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ./hardware-configuration.nix
    ../../core
  ];
  networking.hostName = "latitude";
  boot = {
    # My Legacy Boot
    initrd.luks.devices = [{
      name = "boot";
      device = "/dev/sda2";
      preLVM = true;
    }];
    # Use ufi
    loader.systemd-enable = true;
    loader.efi.canTouchEfiVariables = true;
  };
}