# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
# https://gist.github.com/martijnvermaat/76f2e24d0239470dd71050358b4d5134
{ config, lib, pkgs, ... }:

{
  imports = [
    <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ./hardware-configuration.nix
    ../../core
  ];

  networking.hostName = "dafiti";

  # Supposedly better for the SSD.
  fileSystems."/".options = [ "noatime" "nodiratime" "discard" ];

  boot = {
    # My Legacy Boot
    initrd.luks.devices = [{
      name = "boot";
      device = "/dev/sda2";
      preLVM = true;
      allowDiscards = true;
    }];

    # Use the GRUB 2 boot loader.
    loader.grub.enable = true;
    loader.grub.version = 2;
    loader.grub.device = "nodev";
    loader.grub.efiSupport = true;
    loader.efi.canTouchEfiVariables = true;
  };
}
